"""remove timezone from ai messages

Revision ID: 4cb5e9817576
Revises: c04869c0b8a5
Create Date: 2025-01-23 21:49:25.299739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cb5e9817576'
down_revision: Union[str, None] = 'c04869c0b8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kols_id', table_name='kols')
    op.drop_index('ix_kols_platform_user_id', table_name='kols')
    op.drop_table('kols')
    op.drop_table('attachments')
    op.drop_table('messages')
    op.drop_table('unread_messages')
    op.drop_index('ix_ai_messages_channel_id', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_table('channels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('channels_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('platform_channel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('guild_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_forwarding', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('kol_category', postgresql.ENUM('CRYPTO', 'STOCKS', 'FUTURES', 'FOREX', 'OTHERS', name='kolcategory'), autoincrement=False, nullable=True),
    sa.Column('kol_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='channels_pkey'),
    sa.UniqueConstraint('platform_channel_id', name='channels_platform_channel_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('channel_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ai_messages_pkey')
    )
    op.create_index('ix_ai_messages_channel_id', 'ai_messages', ['channel_id'], unique=False)
    op.create_table('unread_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_read_message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unread_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name='unread_messages_channel_id_fkey'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], name='unread_messages_last_read_message_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='unread_messages_pkey')
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('messages_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('platform_message_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kol_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embeds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('referenced_message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('referenced_content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name='messages_channel_id_fkey'),
    sa.ForeignKeyConstraint(['kol_id'], ['kols.id'], name='messages_kol_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey'),
    sa.UniqueConstraint('platform_message_id', name='messages_platform_message_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='attachments_message_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='attachments_pkey')
    )
    op.create_table('kols',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platform_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='kols_pkey')
    )
    op.create_index('ix_kols_platform_user_id', 'kols', ['platform_user_id'], unique=False)
    op.create_index('ix_kols_id', 'kols', ['id'], unique=False)
    # ### end Alembic commands ###
