"""allow null message_id in attachments

Revision ID: e915f03f6ae8
Revises: add_channel_category_fields
Create Date: 2025-01-20 13:36:09.639491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e915f03f6ae8'
down_revision: Union[str, None] = 'add_channel_category_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kols')
    op.drop_table('unread_messages')
    op.drop_table('channels')
    op.drop_table('messages')
    op.drop_table('attachments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='attachments_message_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='attachments_pkey')
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('messages_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('platform_message_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kol_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embeds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('referenced_message_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('referenced_content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name='messages_channel_id_fkey'),
    sa.ForeignKeyConstraint(['kol_id'], ['kols.id'], name='messages_kol_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey'),
    sa.UniqueConstraint('platform_message_id', name='messages_platform_message_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('channels',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('channels_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('platform_channel_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('guild_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('kol_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kol_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='channels_pkey'),
    sa.UniqueConstraint('platform_channel_id', name='channels_platform_channel_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('unread_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_read_message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unread_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name='unread_messages_channel_id_fkey'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], name='unread_messages_last_read_message_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='unread_messages_pkey')
    )
    op.create_table('kols',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='kols_pkey'),
    sa.UniqueConstraint('platform_user_id', name='kols_platform_user_id_key')
    )
    # ### end Alembic commands ###
